mode: parallel #模式 balance(均衡模式)、parallel(平行模式)
containers: #容器，可配置多个
  - address: http://xxx.xxx.xxx.xxx:5700 #青龙2.2、青龙2.8、v1v2v3v4v5访问地址
    username: xxx #用户名
    password: xxx #密码
    weigth: 3 #权重 balance模式下权重越高分得的ck越多，默认1
    mode: parallel #单独对容器进行模式设置
    limit: 50 #限制容器ck数目
theme: ./theme/summer.html #自定义主题，支持本地、网络路径
static: ./static #静态文件 便于自定义二维码页面时，引入css、js等文件
master: xxxx #管理员账户pin，有多个用'&'拼接
database: /ql/JDC/XDD.db #数据库位置
qywx_key:  #企业微信推送key
daily_push: #定时任务
resident: #均衡模式下所有容器共同的账号pin，有多个用'&'拼接。不建议填写，后续实现指定账号助力功能。

user_agent: #自定义ua
telegram_bot_token: #telegram bot token
telegram_user_id: #telegrame user id
qquid: #接收通知的qq号
qqgid: #监听的群
qbot_public_mode: true

default_priority: #新用户默认优先级
no_ghproxy: true #更新资源是否不使用代理 默认false
daily_asset_push_cron:  #日常资产推送时间
repos:
  - git: https://github.com/shufflewzc/faker2.git
